#!/usr/bin/env bash
set -e
VERSION1="${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-jetson-jp${JETPACK_MAJOR}.${JETPACK_MINOR}"
VERSION2="${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-l4t-r${L4T_MAJOR_VERSION}.${L4T_MINOR_VERSION}"
#IMAGE_PATH="zed-docker/${ZED_SDK_MAJOR}.X/l4t_${L4T_MAJOR_VERSION}.X/${IMAGE_VARIANT}"
IMAGE_PATH="zed-docker/${ZED_SDK_MAJOR}.X/l4t/${IMAGE_VARIANT}"
docker info
docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
docker build --no-cache --build-arg L4T_MAJOR_VERSION=${L4T_MAJOR_VERSION} --build-arg L4T_MINOR_VERSION=${L4T_MINOR_VERSION} --build-arg L4T_PATCH_VERSION=${L4T_PATCH_VERSION} --build-arg ZED_SDK_MAJOR=${ZED_SDK_MAJOR} --build-arg ZED_SDK_MINOR=${ZED_SDK_MINOR} --build-arg L4T_BASE_IMAGE=${L4T_BASE_IMAGE} -t "${CI_REGISTRY_IMAGE}:${VERSION1}" "${IMAGE_PATH}"
docker build --build-arg L4T_MAJOR_VERSION=${L4T_MAJOR_VERSION} --build-arg L4T_MINOR_VERSION=${L4T_MINOR_VERSION} --build-arg L4T_PATCH_VERSION=${L4T_PATCH_VERSION} --build-arg ZED_SDK_MAJOR=${ZED_SDK_MAJOR} --build-arg ZED_SDK_MINOR=${ZED_SDK_MINOR} --build-arg L4T_BASE_IMAGE=${L4T_BASE_IMAGE} -t "${CI_REGISTRY_IMAGE}:${VERSION2}" "${IMAGE_PATH}"
docker tag "${CI_REGISTRY_IMAGE}:${VERSION1}" "${CI_REGISTRY_IMAGE}:${VERSION1}";
docker tag "${CI_REGISTRY_IMAGE}:${VERSION2}" "${CI_REGISTRY_IMAGE}:${VERSION2}";
docker push "${CI_REGISTRY_IMAGE}:${VERSION1}"
docker push "${CI_REGISTRY_IMAGE}:${VERSION2}"